version: "3.9"

services:
  flask:
    build:
      context: ./app
    image: local/flask-uwsgi:py38
    container_name: msrp_flask
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: msrp_redis
    networks:
      - backend

  nginx:
    image: nginx:1.25
    container_name: msrp_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    networks:
      - backend

networks:
  backend:
    driver: bridge
