version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example_root_password
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8080:80"
volumes:
  db_data:
