services:
  redis:
    image: redis:alpine
    command: ["redis-server","--appendonly","yes","--requirepass","s3cr3t"]
    networks:
      - appnet

  web:
    image: redis:alpine
    environment:
      REDIS_PASSWORD: s3cr3t
    depends_on:
      - redis
    command: sh -c 'until redis-cli -h redis -a "$REDIS_PASSWORD" PING; do echo waiting; sleep 1; done; echo "Connected to Redis"; tail -f /dev/null'
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
