name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    # ... (השאר את הבלוק הזה ללא שינוי)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  build-and-push:
    needs: test
    if: success()
    uses: ./.github/workflows/build-and-push.yml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
